// Service worker: answers only <scope>zip/… with a zip assembled while it streams, so the browser's own download
// manager saves any size with a real progress bar and nothing is held in memory. Nothing outside zip/ is ever
// intercepted, so this worker cannot serve a stale page. build.mjs prepends zip.mjs (ZipWriter) to this file.
//
//   zip/<org>/<name>/auto.zip              every file, each from the first source that answers
//   zip/<org>/<name>/<source kind>.zip     only that source (files it lacks are left out)
//   zip/_proof/<spec>.zip                  generated bytes, no network (qa/zip-proof)
//
// Every file is hashed while it streams and compared with its address from the index; a mismatch errors the stream,
// so the browser marks the download failed. The source only supplies bytes; it is never trusted.
/* global ZipWriter, hashwasm */

const MiB = 1024 * 1024;
const SCOPE = new URL(self.registration.scope);
importScripts(new URL("vendor/hash-wasm/sha256.umd.min.js", SCOPE).href);

const channel = new BroadcastChannel("model-hub-zip");
const running = new Map(); // id → AbortController

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => event.waitUntil(self.clients.claim()));
// The page pings while a download runs (keeps this worker alive) and may cancel one.
self.addEventListener("message", (event) => { if (event.data?.cancel) running.get(event.data.cancel)?.abort(); });

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url), prefix = `${SCOPE.pathname}zip/`;
  if (url.origin !== SCOPE.origin || !url.pathname.startsWith(prefix)) return;
  event.respondWith(answer(decodeURIComponent(url.pathname.slice(prefix.length)), url, event.request).catch((error) => new Response(String(error.message || error), { status: 502 })));
});

// A byte stream the consumer paces: write() resolves only when the download wants more, so a slow disk slows the
// producer instead of filling memory.
function paced(abort, run) {
  let wake = null;
  abort.signal.addEventListener("abort", () => wake?.());
  return new ReadableStream({
    start(controller) {
      const write = async (bytes) => {
        if (abort.signal.aborted) throw new Error("cancelled");
        controller.enqueue(bytes);
        while (controller.desiredSize <= 0 && !abort.signal.aborted) await new Promise((resolve) => { wake = resolve; });
      };
      run(write).then(() => controller.close(), (error) => { try { controller.error(error); } catch { /* already cancelled */ } });
    },
    pull() { wake?.(); wake = null; },
    cancel() { abort.abort(); },
  }, { highWaterMark: 8 * MiB, size: (chunk) => chunk.byteLength });
}

// One zip download. `entries` = [{ name, size, … }]; `open(entry, i, signal)` returns that entry's byte stream;
// `check(entry, digestHex)` throws when the bytes are not the ones the index names.
function download({ id, filename, entries, open, check, tail }, request) {
  const total = ZipWriter.sizeOf(entries);
  const headers = { "Content-Type": "application/zip", "Content-Disposition": `attachment; filename="${filename}"`, "Content-Length": String(total), "Cache-Control": "no-store" };
  if (request.method === "HEAD") return new Response(null, { headers });
  running.get(id)?.abort(); // one download per model at a time
  const abort = new AbortController();
  running.set(id, abort);
  let sent = 0, files = 0, last = 0;
  const report = (state, detail) => channel.postMessage({ id, state, sent, total, files, count: entries.length, filename, detail });
  const body = paced(abort, async (write) => {
    const zip = new ZipWriter(async (bytes) => {
      await write(bytes);
      sent += bytes.length;
      if (Date.now() - last > 250) { last = Date.now(); report("running"); }
    });
    try {
      report("running");
      for (let i = 0; i < entries.length; i++) {
        const entry = entries[i];
        if (entry.tail) { await zip.add(entry.name, entry.size, bytesStream(tail(entry))); files++; continue; }
        const hasher = check ? await hashwasm.createSHA256() : null;
        hasher?.init();
        await zip.add(entry.name, entry.size, await open(entry, i, abort.signal), hasher ? (chunk) => hasher.update(chunk) : undefined);
        if (hasher) check(entry, hasher.digest("hex"));
        files++;
      }
      await zip.finish();
      report("done");
    } catch (error) {
      report(abort.signal.aborted ? "cancelled" : "failed", String(error.message || error));
      throw error;
    } finally {
      if (running.get(id) === abort) running.delete(id);
    }
  });
  return new Response(body, { headers });
}

const bytesStream = (bytes) => new ReadableStream({ start(controller) { if (bytes.length) controller.enqueue(bytes); controller.close(); } });
const encodePath = (path) => path.split("/").map(encodeURIComponent).join("/");
const sleep = (ms, signal) => new Promise((resolve) => { const t = setTimeout(resolve, ms); signal.addEventListener("abort", () => { clearTimeout(t); resolve(); }, { once: true }); });

// ---- a model: bytes from the sources, names and addresses from the index
const SOURCE_ORDER = ["huggingface.co", "modelscope.cn", "ipfs"];
const SMALL = 4 * MiB, WINDOW = 6;

// One file's bytes as a stream that survives a dropped connection: it asks again from the byte it reached (Range),
// from the same source and then from the next. Same bytes by definition; the running hash proves it.
function resilient(entry, signal, note) {
  let received = 0, reader = null, at = 0, tries = 0;
  async function connect() {
    for (; at < entry.urls.length; at++, tries = 0) {
      for (; tries < 4; tries++) {
        if (signal.aborted) throw new Error("cancelled");
        if (tries) await sleep(500 * 2 ** tries, signal);
        try {
          const response = await fetch(entry.urls[at].url, { signal, headers: received ? { Range: `bytes=${received}-` } : {} });
          if (!response.ok || !response.body) { if (response.status === 404 || response.status === 403) break; continue; }
          let body = response.body.getReader();
          if (received && response.status !== 206) body = skipping(body, received); // the source ignored Range
          entry.from = at;
          return body;
        } catch { /* network error or CORS refusal: try again, then the next source */ }
      }
      note?.(`${entry.urls[at].kind} did not deliver ${entry.name}`);
    }
    throw new Error(`No source delivered ${entry.name}.`);
  }
  return new ReadableStream({
    async pull(controller) {
      for (;;) {
        try {
          reader ||= await connect();
          const { value, done } = await reader.read();
          if (done) {
            if (received < entry.size) { reader = null; tries++; continue; } // cut short: resume
            controller.close();
            return;
          }
          received += value.byteLength;
          if (received > entry.size) throw new Error(`${entry.urls[at].kind} sent more than ${entry.size} bytes for ${entry.name}.`);
          controller.enqueue(value);
          return;
        } catch (error) {
          if (signal.aborted || /No source delivered|sent more than/.test(error.message)) { controller.error(error); return; }
          reader = null; tries++;
          if (tries >= 4) { at++; tries = 0; }
        }
      }
    },
    cancel() { reader?.cancel().catch(() => {}); },
  });
}
function skipping(reader, skip) {
  let left = skip;
  return { async read() { for (;;) { const r = await reader.read(); if (r.done || !left) return r; if (r.value.byteLength <= left) { left -= r.value.byteLength; continue; } const value = r.value.subarray(left); left = 0; return { value, done: false }; } }, cancel: () => reader.cancel() };
}

async function model(org, name, source, request) {
  const doc = await fetch(new URL(`data/files/${encodePath(org)}/${encodePath(name)}.json`, SCOPE)).then((r) => { if (!r.ok) throw new Error("This model has no file index."); return r.json(); });
  const sources = (doc.sources || []).filter((s) => !s.p2p && !s.pull && (source === "auto" || s.kind === source));
  sources.sort((a, b) => SOURCE_ORDER.indexOf(a.kind) - SOURCE_ORDER.indexOf(b.kind));
  if (!sources.length) throw new Error(`This model is not on ${source}.`);
  const entries = [];
  for (const [path, size, address, , hfUrl] of doc.files) {
    const urls = sources.filter((s) => !(s.missing || []).includes(path)).map((s) => ({ kind: s.kind, url: s.kind === "huggingface.co" ? hfUrl : s.resolve + encodePath(path) })).filter((u) => u.url);
    if (urls.length) entries.push({ name: path, size: size || 0, address, urls, from: 0 });
  }
  // Two small files make the zip check itself offline, forever. Their size is fixed before the first byte: the record
  // of which source delivered each file is one digit per file.
  const sums = new TextEncoder().encode(entries.map((e) => `${e.address.split(":")[1]}  ${e.name}\n`).join(""));
  const created = new Date().toISOString().slice(0, 19) + "Z";
  const record = () => new TextEncoder().encode(`${JSON.stringify({ format: "hologram.model-hub.zip/v1", model: `${org}/${name}`, revision: doc.revision, manifest: doc.manifest, created, sources: sources.map((s) => s.kind), files: entries.filter((e) => !e.tail).map((e) => [e.name, e.address, e.from]) })}\n`);
  entries.push({ name: "SHA256SUMS", size: sums.length, tail: "sums" }, { name: "HOLOGRAM.json", size: record().length, tail: "record" });

  // Small files are fetched a few at a time (latency dominates); a large file has the next one already requested.
  const ahead = new Map();
  const begin = (i, signal) => {
    const e = entries[i];
    if (!e || e.tail || ahead.has(i)) return;
    ahead.set(i, e.size <= SMALL ? new Response(resilient(e, signal)).arrayBuffer().then((b) => bytesStream(new Uint8Array(b))) : Promise.resolve(resilient(e, signal)));
    ahead.get(i).catch(() => {});
  };
  const gateway = (e) => e && !e.tail && e.urls[0].kind === "ipfs";
  return download({
    id: `${org}/${name}`, filename: `${name}-${doc.revision.slice(0, 8)}.zip`, entries,
    open(entry, i, signal) {
      begin(i, signal);
      const window = gateway(entry) ? 2 : WINDOW; // the IPFS gateway answers 429 above a few parallel requests
      for (let k = 1, small = 0; k <= window && small < window; k++) { const next = entries[i + k]; if (!next || next.tail) break; if (next.size <= SMALL || k === 1) { begin(i + k, signal); small++; } }
      const stream = ahead.get(i);
      ahead.delete(i);
      return stream;
    },
    check(entry, hex) { if (`sha256:${hex}` !== entry.address) throw new Error(`${entry.urls[entry.from]?.kind || "A source"} served different bytes for ${entry.name}. Nothing was kept.`); },
    tail: (entry) => (entry.tail === "sums" ? sums : record()),
  }, request);
}

// ---- zip/_proof/<spec>.zip: generated bytes, no network. Proves the transport (size, memory, worker lifetime).
function proofEntries(spec) {
  const small = Array.from({ length: 100 }, (_, i) => ({ name: `small/${i}.txt`, size: 1024 + i }));
  if (spec === "tiny") return [{ name: "a.bin", size: 3 * MiB + 17 }, ...small];
  if (spec === "6g") return [{ name: "weights-00001.bin", size: 4608 * MiB + 3 }, { name: "weights-00002.bin", size: 1024 * MiB }, ...small];
  throw new Error(`unknown proof ${spec}`);
}
const pattern = new Uint8Array(MiB).map((_, i) => (i * 31 + (i >> 8)) & 0xff);
function generated(size, rate) { // rate: bytes per second, to stand in for a network; 0 = as fast as possible
  let left = size;
  const started = Date.now();
  return new ReadableStream({
    async pull(controller) {
      if (left <= 0) { controller.close(); return; }
      if (rate) { const due = ((size - left) / rate) * 1000 - (Date.now() - started); if (due > 0) await new Promise((r) => setTimeout(r, due)); }
      const n = Math.min(left, pattern.length);
      controller.enqueue(pattern.slice(0, n));
      left -= n;
    },
  });
}

async function answer(path, url, request) {
  const proof = path.match(/^_proof\/([a-z0-9]+)\.zip$/);
  if (proof) return download({ id: `proof:${proof[1]}`, filename: `proof-${proof[1]}.zip`, entries: proofEntries(proof[1]), open: (entry) => generated(entry.size, Number(url.searchParams.get("rate") || 0) * MiB) }, request);
  const m = path.match(/^([^/]+)\/([^/]+)\/(auto|huggingface\.co|modelscope\.cn|ipfs)\.zip$/);
  if (m) return model(m[1], m[2], m[3], request);
  return new Response("unknown zip", { status: 404 });
}
